# zero_deg: angle (0-180) that corresponds to neutral position
# direction: 1 = normal, -1 = reversed
# min_pulse/max_pulse: PWM pulse width range in microseconds (default 750/2250)
#   adjust these to shift the angle mapping without moving the horn

FL:
  shoulder: { channel: 0, zero_deg:  95, direction:  1, kit: 1 }
  leg:      { channel: 1, zero_deg:  89, direction: -1, kit: 1 }
  foot:     { channel: 2, zero_deg: 137, direction: -1, kit: 1 }

FR:
  shoulder: { channel: 4, zero_deg:  81, direction:  -1, kit: 1  }
  leg:      { channel: 5, zero_deg: 132, direction:   1, kit: 1  }
  foot:     { channel: 6, zero_deg:  62, direction:   1, kit: 1  }

RL:
  shoulder: { channel:  15, zero_deg:  75, direction:  -1, kit: 2  }
  leg:      { channel:  13, zero_deg:  76, direction:  -1, kit: 2  }
  foot:     { channel:  12, zero_deg: 120, direction:  -1, kit: 2  }

RR:
  shoulder: { channel: 0, zero_deg: 90, direction:  1, kit: 2  }
  leg:      { channel: 1, zero_deg: 94, direction:  1, kit: 2  }
  foot:     { channel: 2, zero_deg: 50, direction:  1, kit: 2 }